server.port=${SERVER_PORT:8081}
spring.application.name=data-ingest-service

# --- STORAGE BLOB CONFIG ---
spring.cloud.azure.storage.blob.account-name=${STORAGE_ACCOUNT_NAME}
spring.cloud.azure.storage.blob.endpoint=${STORAGE_BLOB_ENDPOINT}
spring.cloud.azure.storage.blob.container-name=${REPORT_CONTAINER}

# --- EVENT HUBS CONFIG ---
spring.cloud.azure.eventhubs.namespace=${AZURE_EVENTHUBS_NAMESPACE}
spring.cloud.function.definition=reportConsumer;reportConsumer1
spring.cloud.stream.bindings.reportConsumer-in-0.destination=${EVENTHUB_DESTINATION}
spring.cloud.stream.bindings.reportConsumer-in-0.group=${EVENTHUB_GROUP}
spring.cloud.stream.eventhubs.bindings.reportConsumer-in-0.consumer.checkpoint.mode=RECORD
spring.cloud.stream.bindings.reportConsumer1-in-0.destination=${EVENTHUB_DESTINATION}
spring.cloud.stream.bindings.reportConsumer1-in-0.group=${EVENTHUB_GROUP}
spring.cloud.stream.eventhubs.bindings.reportConsumer1-in-0.consumer.checkpoint.mode=RECORD
# --- CHECKPOINT STORE CONFIG ---
spring.cloud.azure.eventhubs.processor.checkpoint-store.account-name=${STORAGE_ACCOUNT_NAME}
spring.cloud.azure.eventhubs.processor.checkpoint-store.container-name=${CHECKPOINT_CONTAINER}

# --- COSMOS DB CONFIG ---
spring.cloud.azure.cosmos.endpoint=${COSMOS_ENDPOINT}
spring.cloud.azure.cosmos.database=${COSMOS_DATABASE}

logging.level.com.azure.messaging.eventhubs=${AZURE_LOG_LEVEL:WARN}

management.endpoints.web.exposure.include=prometheus