server.port=${SERVER_PORT:8081}
spring.application.name=data-ingest-service

# --- STORAGE BLOB CONFIG ---
spring.cloud.azure.storage.blob.account-name=${STORAGE_ACCOUNT_NAME}
spring.cloud.azure.storage.blob.endpoint=${STORAGE_BLOB_ENDPOINT}
spring.cloud.azure.storage.blob.container-name=${REPORT_CONTAINER}

# --- EVENT HUBS CONFIG ---
spring.cloud.azure.eventhubs.namespace=${AZURE_EVENTHUBS_NAMESPACE}
spring.cloud.function.definition=reportConsumer

spring.cloud.stream.bindings.reportConsumer-in-0.destination=${EVENTHUB_DESTINATION}
spring.cloud.stream.bindings.reportConsumer-in-0.group=${EVENTHUB_GROUP:report-service-group}
spring.cloud.stream.bindings.reportConsumer-in-0.consumer.multiplex=true

spring.cloud.stream.eventhubs.bindings.reportConsumer-in-0.consumer.checkpoint.mode=RECORD

spring.cloud.azure.eventhubs.processor.start-position=earliest

# --- COSMOS DB CONFIG ---
spring.cloud.azure.cosmos.endpoint=${COSMOS_ENDPOINT}
spring.cloud.azure.cosmos.database=${COSMOS_DATABASE}

# --- CHECKPOINT STORE CONFIG ---
spring.cloud.azure.eventhubs.processor.checkpoint-store.account-name=${STORAGE_ACCOUNT_NAME}
spring.cloud.azure.eventhubs.processor.checkpoint-store.container-name=${CHECKPOINT_CONTAINER}

logging.level.com.azure.messaging.eventhubs=${AZURE_LOG_LEVEL:WARN}

management.endpoints.web.exposure.include=prometheus